services:
  maketa_app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: maketa_app
    restart: always
    ports:
      - "5001:5000"
    env_file:
      - ./backend/.env
    environment:
      - DATABASE_URL_LOCAL=
      - FLASK_DEBUG=0
    depends_on:
      maketa_db:
        condition: service_healthy
    volumes:
      - ./backend:/app

  maketa_db:
    image: postgres:16
    container_name: maketa_db
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-admin} -d ${POSTGRES_DB:-maketa_db}"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: