name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: SSH into VPS and deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo "[INFO] Criando backup do banco..."
            mkdir -p ~/backups
            docker exec maketa_db pg_dump -U admin maketa_db > ~/backups/maketa_backup_$(date +'%Y%m%d_%H%M%S').dump

            echo "[INFO] Atualizando aplicação..."
            cd ~/MAKETA
            git reset --hard
            git pull origin main

            echo "[INFO] Reconstruindo containers..."
            docker compose up -d --build

            echo "[INFO] Deploy finalizado com sucesso!"