name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: SSH into VPS and deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            set -euo pipefail
            echo "[INFO] Criando backup do banco..."
            mkdir -p ~/backups
            docker exec maketa_db pg_dump -U admin maketa_db > ~/backups/maketa_backup_$(date +'%Y%m%d_%H%M%S').dump

            echo "[INFO] Atualizando aplicação..."
            cd ~/Maketa/MAKETA
            git reset --hard
            git pull origin main

            echo "[INFO] Derrubando containers (mantendo volumes)..."
            docker compose down

            echo "[INFO] Subindo containers (build + remove órfãos)..."
            docker compose up -d --build --remove-orphans

            echo "[INFO] Verificando saúde da aplicação..."
            curl -sSf http://localhost:5001/health | jq . || (echo "[ERRO] Health check falhou" && exit 1)

            echo "[INFO] Deploy finalizado com sucesso!"